PAYMENT_STATUS = [
    ("PENDING", "PENDING"),
    ("COMPLETED", "COMPLETED"),
    ("FAILED", "FAILED"),
]

PAYMENT_METHOD = [
    ("CREDIT_CARD", "CREDIT_CARD"),
    ("DEBIT_CARD", "DEBIT_CARD"),
    ("COD", "COD"),
    ("PHONEPAY", "PHONEPAY"),
    ("GPAY", "GPAY"),
    ("PAYTM", "PAYTM"),
]
